name: Update Credly Badges
on:
  schedule:
    - cron: "0 2 * * *" # Runs at 2am UTC daily
  workflow_dispatch:

permissions:
  contents: write  # Required to update README.md

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: alan-alan-clucas-org
